# Embedding Layer 

In [51]:
from tensorflow.keras.preprocessing.text import one_hot

In [52]:
### sentences

sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [53]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [54]:
## next we need to define the vocabulary size (number of unique tokens)

voc_size = 10000 

In [55]:
##one hot representation

one_hot_rep = [one_hot(words,voc_size)for words in sent]
one_hot_rep

[[9577, 5484, 6974, 827],
 [9577, 5484, 6974, 2844],
 [9577, 6330, 6974, 7514],
 [1049, 8377, 6087, 6397, 9002],
 [1049, 8377, 6087, 6397, 8482],
 [9365, 9577, 9516, 6974, 4466],
 [7017, 2631, 3054, 6397]]

In [56]:
## word embedding representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [57]:
import numpy as np


In [58]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)

#to get the zeros after the numbers we can use post
# embedded_docs = pad_sequences(one_hot_rep,padding='post',maxlen=sent_length)

print(embedded_docs)

[[   0    0    0    0 9577 5484 6974  827]
 [   0    0    0    0 9577 5484 6974 2844]
 [   0    0    0    0 9577 6330 6974 7514]
 [   0    0    0 1049 8377 6087 6397 9002]
 [   0    0    0 1049 8377 6087 6397 8482]
 [   0    0    0 9365 9577 9516 6974 4466]
 [   0    0    0    0 7017 2631 3054 6397]]


In [59]:
## feature representation

dim=10   # here we can use any number of dimensions in the  word embeddings and each word is mapped to 10 dimensianl vecotr


In [64]:
model=Sequential() # define the model 
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse') # here I am using adam optimizer and loss function mse to train the model





In [ ]:
model.build(input_shape=(None,8)) # tp build the model expicity if needed 
model.summary() # print the model 

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [67]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step


array([[[-0.01856043,  0.02867868, -0.00132066, -0.04956889,
         -0.03314698,  0.03701599, -0.03074697, -0.01793864,
         -0.01061746,  0.02718912],
        [-0.01856043,  0.02867868, -0.00132066, -0.04956889,
         -0.03314698,  0.03701599, -0.03074697, -0.01793864,
         -0.01061746,  0.02718912],
        [-0.01856043,  0.02867868, -0.00132066, -0.04956889,
         -0.03314698,  0.03701599, -0.03074697, -0.01793864,
         -0.01061746,  0.02718912],
        [-0.01856043,  0.02867868, -0.00132066, -0.04956889,
         -0.03314698,  0.03701599, -0.03074697, -0.01793864,
         -0.01061746,  0.02718912],
        [ 0.02848228,  0.03618405,  0.02820368,  0.01974512,
          0.0436721 , -0.01919529,  0.04677734, -0.02732869,
         -0.00778879, -0.00692953],
        [ 0.02399779, -0.00149089,  0.02948098,  0.01741979,
         -0.03917223,  0.02295658,  0.04122937, -0.04069476,
          0.03019667, -0.03848013],
        [ 0.04057921,  0.00501452,  0.04254958, -0.0

In [68]:
embedded_docs[0]

array([   0,    0,    0,    0, 9577, 5484, 6974,  827], dtype=int32)

In [74]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


array([[[-0.01856043,  0.02867868, -0.00132066, -0.04956889,
         -0.03314698,  0.03701599, -0.03074697, -0.01793864,
         -0.01061746,  0.02718912],
        [-0.01856043,  0.02867868, -0.00132066, -0.04956889,
         -0.03314698,  0.03701599, -0.03074697, -0.01793864,
         -0.01061746,  0.02718912],
        [-0.01856043,  0.02867868, -0.00132066, -0.04956889,
         -0.03314698,  0.03701599, -0.03074697, -0.01793864,
         -0.01061746,  0.02718912],
        [-0.01856043,  0.02867868, -0.00132066, -0.04956889,
         -0.03314698,  0.03701599, -0.03074697, -0.01793864,
         -0.01061746,  0.02718912],
        [ 0.02848228,  0.03618405,  0.02820368,  0.01974512,
          0.0436721 , -0.01919529,  0.04677734, -0.02732869,
         -0.00778879, -0.00692953],
        [ 0.02399779, -0.00149089,  0.02948098,  0.01741979,
         -0.03917223,  0.02295658,  0.04122937, -0.04069476,
          0.03019667, -0.03848013],
        [ 0.04057921,  0.00501452,  0.04254958, -0.0